## Some more NumPy useful Functions


In [1]:
import numpy as np

In [13]:
a = np.array([10, 12, 39, 44, 45, 26, 97, 18, 90, 101])

In [15]:
print(a.shape)

print(a.reshape(2, 5))

print(np.argsort(a))

(10,)
[[ 10  12  39  44  45]
 [ 26  97  18  90 101]]
[0 1 7 5 2 3 4 8 6 9]
